#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define ID_FILE_SAVE                            200
#define ID_FILE_REN                             201
#define ID_FILE_EXIT                            202
#define ID_FILE_SETTINGS                        203
#define ID_FILE_EXPORTEXCEL                     204
#define ID_FILE_NEW                             206
#define ID_FILE_OPEN                            207
#define ID_FILE_PASS                            208
#define ID_OPS_CPY                              300
#define ID_OPS_EDIT                             301
#define ID_OPS_NEWDEP                           303
#define ID_OPS_NEWWITH                          304
#define ID_OPS_PASTE                            305
#define ID_OPS_REM                              306
#define ID_OPS_STARTBAL                         307
#define ID_NEGAT                                308
#define ID_GOTO                                 309
#define ID_HELP_ABT                             400
#define ID_HELP_HLP                             401
#define IDC_ABOUTTEXT                           402
#define IDC_ABOUTTEXT1                          403
#define IDC_ABT_LOG                             404
#define ABOUTDLG                                405
#define ID_FIND_CAT                             501
#define ID_FIND_DESCR                           502
#define ID_SYS_CASC                             505
#define IDC_DATE                                600
#define IDC_QTY                                 601
#define IDC_VAL                                 602
#define IDC_VAL_CENTS                           603
#define IDC_CAT                                 605
#define IDC_DESCR                               607
#define IDC_WD_OKNEW                            608
#define WDDLG                                   609
#define ID_DEL                                  700
#define TRNSOPENDLG                             701
#define ID_RENAME                               702
#define IDC_OPENLIST                            703
#define IDC_PASS                                704
#define SETPASSDLG                              705
#define IDC_PASS1                               706
#define IDC_REMPASS                             707
#define ID_TOTBAL                               708
#define IDC_WP_CNTR                             800
#define WNDPOSDLG                               801
#define IDC_WP_HEIGHT                           802
#define IDC_WP_WID                              803
#define IDC_WP_XPOS                             804
#define IDC_WP_YPOS                             805
#define IDC_PREF_AUTOSV                         900
#define PREFDLG                                 901
#define IDC_PREF_AUTOSV_SB                      902
#define IDC_PREF_ISAUTOSV                       903
#define IDC_PREF_TAX                            904
#define IDC_PREF_FONT                           906
#define IDC_AMTWID                              1000
#define COLWIDTHDLG                             1001
#define IDC_AMT_SB                              1002
#define IDC_CATWID                              1003
#define IDC_CAT_SB                              1004
#define IDC_BALWID                              1005
#define IDC_BAL_SB                              1006
#define IDC_DATWID                              1007
#define IDC_DAT_SB                              1008
#define IDC_DESCRWID                            1011
#define IDC_DESCR_SB                            1012
#define IDC_INPUT_DESCR                         1100
#define INPUTDLG                                1101
#define IDC_INPUT_THIRD                         1102
#define IDC_INPUT_USER                          1103
#define IDR_MENU                                1300
#define IDM_SPLITMENU                           1301
#define IDR_ACCEL                               1302
#define ID_CTXMENU                              1303
#define IDM_FINDSPLITMENU                       1305
#define IDI_APPICO                              1400
#define IDI_NEWTRANS                            1401
#define IDI_EDITTRANS                           1402
#define IDI_TB_NEW                              1403
#define IDI_TB_OPEN                             1404
#define IDI_TB_SAVE                             1405
#define IDI_TB_DEL                              1406
#define IDB_LOGO                                1407
#define IDI_TB_FIND                             1408
#define IDI_EXCEL                               1409
#define IDI_CPY                                 1410
#define IDI_PST                                 1411
#define IDS_CAT_COL                             40000
#define IDS_DESCR_COL                           40001
#define IDS_DATE_COL                            40002
#define IDS_AMT_COL                             40003
#define IDS_BAL_COL                             40004
#define ID_SYS_ABT                              40005
#define ID_SYS_TILE                             40006
#define IDC_QTY_UNPRC                           40007
#define IDC_QTY_UNPRC_CNTS                      40008
#define IDC_QTY_RES                             40009
#define QTYDLG                                  40010
#define TUTDLG                                  40011
#define ID_TUT_SHOWHLP                          40012
#define ID_TUT_MODCONFIG                        40013
#define ID_TUT_EXIT                             40014
#define ID_FILE_REMOVE                          40015
#define ID_OPS_CUT                              40016
#define IDI_CUT                                 40017
#define ID_DN                                   40018
#define ID_UP                                   40019
#define ID_FULLSCREEN                           40020
#define ID_HELP_4PROG                           40021
#define SEGFAULTDLG                             40022
